// Code generated by MockGen. DO NOT EDIT.
// Source: core/datastore/types.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	datastore "github.com/s8sg/goflow/core/datastore"
)

// MockScanIterator is a mock of ScanIterator interface.
type MockScanIterator struct {
	ctrl     *gomock.Controller
	recorder *MockScanIteratorMockRecorder
}

// MockScanIteratorMockRecorder is the mock recorder for MockScanIterator.
type MockScanIteratorMockRecorder struct {
	mock *MockScanIterator
}

// NewMockScanIterator creates a new mock instance.
func NewMockScanIterator(ctrl *gomock.Controller) *MockScanIterator {
	mock := &MockScanIterator{ctrl: ctrl}
	mock.recorder = &MockScanIteratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScanIterator) EXPECT() *MockScanIteratorMockRecorder {
	return m.recorder
}

// Err mocks base method.
func (m *MockScanIterator) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockScanIteratorMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockScanIterator)(nil).Err))
}

// Next mocks base method.
func (m *MockScanIterator) Next(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockScanIteratorMockRecorder) Next(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockScanIterator)(nil).Next), ctx)
}

// Val mocks base method.
func (m *MockScanIterator) Val() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Val")
	ret0, _ := ret[0].(string)
	return ret0
}

// Val indicates an expected call of Val.
func (mr *MockScanIteratorMockRecorder) Val() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Val", reflect.TypeOf((*MockScanIterator)(nil).Val))
}

// MockDataStorageClient is a mock of DataStorageClient interface.
type MockDataStorageClient struct {
	ctrl     *gomock.Controller
	recorder *MockDataStorageClientMockRecorder
}

// MockDataStorageClientMockRecorder is the mock recorder for MockDataStorageClient.
type MockDataStorageClientMockRecorder struct {
	mock *MockDataStorageClient
}

// NewMockDataStorageClient creates a new mock instance.
func NewMockDataStorageClient(ctrl *gomock.Controller) *MockDataStorageClient {
	mock := &MockDataStorageClient{ctrl: ctrl}
	mock.recorder = &MockDataStorageClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataStorageClient) EXPECT() *MockDataStorageClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDataStorageClient) Delete(ctx context.Context, keys ...string) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDataStorageClientMockRecorder) Delete(ctx interface{}, keys ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataStorageClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockDataStorageClient) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDataStorageClientMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDataStorageClient)(nil).Get), ctx, key)
}

// Ping mocks base method.
func (m *MockDataStorageClient) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDataStorageClientMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDataStorageClient)(nil).Ping), ctx)
}

// Scan mocks base method.
func (m *MockDataStorageClient) Scan(ctx context.Context, cursor uint64, match string, count int64) datastore.ScanIterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", ctx, cursor, match, count)
	ret0, _ := ret[0].(datastore.ScanIterator)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockDataStorageClientMockRecorder) Scan(ctx, cursor, match, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockDataStorageClient)(nil).Scan), ctx, cursor, match, count)
}

// Set mocks base method.
func (m *MockDataStorageClient) Set(ctx context.Context, key string, value interface{}, expirationSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, expirationSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockDataStorageClientMockRecorder) Set(ctx, key, value, expirationSeconds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockDataStorageClient)(nil).Set), ctx, key, value, expirationSeconds)
}
