// Code generated by MockGen. DO NOT EDIT.
// Source: runtime/interfaces.go

// Package mock_runtime is a generated GoMock package.
package mock_runtime

import (
	context "context"
	reflect "reflect"
	time "time"

	rmq "github.com/adjust/rmq/v4"
	redis "github.com/go-redis/redis"
	gomock "github.com/golang/mock/gomock"
	sdk "github.com/s8sg/goflow/core/sdk"
)

// MockRedisClient is a mock of RedisClient interface.
type MockRedisClient struct {
	ctrl     *gomock.Controller
	recorder *MockRedisClientMockRecorder
}

// MockRedisClientMockRecorder is the mock recorder for MockRedisClient.
type MockRedisClientMockRecorder struct {
	mock *MockRedisClient
}

// NewMockRedisClient creates a new mock instance.
func NewMockRedisClient(ctrl *gomock.Controller) *MockRedisClient {
	mock := &MockRedisClient{ctrl: ctrl}
	mock.recorder = &MockRedisClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisClient) EXPECT() *MockRedisClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRedisClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRedisClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedisClient)(nil).Close))
}

// Del mocks base method.
func (m *MockRedisClient) Del(keys ...string) *redis.IntCmd {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Del", varargs...)
	ret0, _ := ret[0].(*redis.IntCmd)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockRedisClientMockRecorder) Del(keys ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockRedisClient)(nil).Del), keys...)
}

// Exists mocks base method.
func (m *MockRedisClient) Exists(keys ...string) *redis.IntCmd {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exists", varargs...)
	ret0, _ := ret[0].(*redis.IntCmd)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockRedisClientMockRecorder) Exists(keys ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockRedisClient)(nil).Exists), keys...)
}

// Get mocks base method.
func (m *MockRedisClient) Get(key string) *redis.StringCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*redis.StringCmd)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRedisClientMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRedisClient)(nil).Get), key)
}

// Ping mocks base method.
func (m *MockRedisClient) Ping() *redis.StatusCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(*redis.StatusCmd)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRedisClientMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRedisClient)(nil).Ping))
}

// Set mocks base method.
func (m *MockRedisClient) Set(key string, value interface{}, expiration time.Duration) *redis.StatusCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value, expiration)
	ret0, _ := ret[0].(*redis.StatusCmd)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRedisClientMockRecorder) Set(key, value, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRedisClient)(nil).Set), key, value, expiration)
}

// MockQueueConnection is a mock of QueueConnection interface.
type MockQueueConnection struct {
	ctrl     *gomock.Controller
	recorder *MockQueueConnectionMockRecorder
}

// MockQueueConnectionMockRecorder is the mock recorder for MockQueueConnection.
type MockQueueConnectionMockRecorder struct {
	mock *MockQueueConnection
}

// NewMockQueueConnection creates a new mock instance.
func NewMockQueueConnection(ctrl *gomock.Controller) *MockQueueConnection {
	mock := &MockQueueConnection{ctrl: ctrl}
	mock.recorder = &MockQueueConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueConnection) EXPECT() *MockQueueConnectionMockRecorder {
	return m.recorder
}

// CollectStats mocks base method.
func (m *MockQueueConnection) CollectStats(queueList []string) (rmq.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectStats", queueList)
	ret0, _ := ret[0].(rmq.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectStats indicates an expected call of CollectStats.
func (mr *MockQueueConnectionMockRecorder) CollectStats(queueList interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectStats", reflect.TypeOf((*MockQueueConnection)(nil).CollectStats), queueList)
}

// GetOpenQueues mocks base method.
func (m *MockQueueConnection) GetOpenQueues() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenQueues")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenQueues indicates an expected call of GetOpenQueues.
func (mr *MockQueueConnectionMockRecorder) GetOpenQueues() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenQueues", reflect.TypeOf((*MockQueueConnection)(nil).GetOpenQueues))
}

// OpenQueue mocks base method.
func (m *MockQueueConnection) OpenQueue(name string) (rmq.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenQueue", name)
	ret0, _ := ret[0].(rmq.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenQueue indicates an expected call of OpenQueue.
func (mr *MockQueueConnectionMockRecorder) OpenQueue(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenQueue", reflect.TypeOf((*MockQueueConnection)(nil).OpenQueue), name)
}

// StopAllConsuming mocks base method.
func (m *MockQueueConnection) StopAllConsuming() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopAllConsuming")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// StopAllConsuming indicates an expected call of StopAllConsuming.
func (mr *MockQueueConnectionMockRecorder) StopAllConsuming() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopAllConsuming", reflect.TypeOf((*MockQueueConnection)(nil).StopAllConsuming))
}

// MockStateStoreFactory is a mock of StateStoreFactory interface.
type MockStateStoreFactory struct {
	ctrl     *gomock.Controller
	recorder *MockStateStoreFactoryMockRecorder
}

// MockStateStoreFactoryMockRecorder is the mock recorder for MockStateStoreFactory.
type MockStateStoreFactoryMockRecorder struct {
	mock *MockStateStoreFactory
}

// NewMockStateStoreFactory creates a new mock instance.
func NewMockStateStoreFactory(ctrl *gomock.Controller) *MockStateStoreFactory {
	mock := &MockStateStoreFactory{ctrl: ctrl}
	mock.recorder = &MockStateStoreFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateStoreFactory) EXPECT() *MockStateStoreFactoryMockRecorder {
	return m.recorder
}

// CreateStateStore mocks base method.
func (m *MockStateStoreFactory) CreateStateStore(redisURI, password string) (sdk.StateStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStateStore", redisURI, password)
	ret0, _ := ret[0].(sdk.StateStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStateStore indicates an expected call of CreateStateStore.
func (mr *MockStateStoreFactoryMockRecorder) CreateStateStore(redisURI, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStateStore", reflect.TypeOf((*MockStateStoreFactory)(nil).CreateStateStore), redisURI, password)
}

// MockDataStoreFactory is a mock of DataStoreFactory interface.
type MockDataStoreFactory struct {
	ctrl     *gomock.Controller
	recorder *MockDataStoreFactoryMockRecorder
}

// MockDataStoreFactoryMockRecorder is the mock recorder for MockDataStoreFactory.
type MockDataStoreFactoryMockRecorder struct {
	mock *MockDataStoreFactory
}

// NewMockDataStoreFactory creates a new mock instance.
func NewMockDataStoreFactory(ctrl *gomock.Controller) *MockDataStoreFactory {
	mock := &MockDataStoreFactory{ctrl: ctrl}
	mock.recorder = &MockDataStoreFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataStoreFactory) EXPECT() *MockDataStoreFactoryMockRecorder {
	return m.recorder
}

// CreateDataStore mocks base method.
func (m *MockDataStoreFactory) CreateDataStore(redisURI, password string) (sdk.DataStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDataStore", redisURI, password)
	ret0, _ := ret[0].(sdk.DataStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDataStore indicates an expected call of CreateDataStore.
func (mr *MockDataStoreFactoryMockRecorder) CreateDataStore(redisURI, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDataStore", reflect.TypeOf((*MockDataStoreFactory)(nil).CreateDataStore), redisURI, password)
}

// MockHTTPServerInterface is a mock of HTTPServerInterface interface.
type MockHTTPServerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPServerInterfaceMockRecorder
}

// MockHTTPServerInterfaceMockRecorder is the mock recorder for MockHTTPServerInterface.
type MockHTTPServerInterfaceMockRecorder struct {
	mock *MockHTTPServerInterface
}

// NewMockHTTPServerInterface creates a new mock instance.
func NewMockHTTPServerInterface(ctrl *gomock.Controller) *MockHTTPServerInterface {
	mock := &MockHTTPServerInterface{ctrl: ctrl}
	mock.recorder = &MockHTTPServerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPServerInterface) EXPECT() *MockHTTPServerInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockHTTPServerInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockHTTPServerInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockHTTPServerInterface)(nil).Close))
}

// ListenAndServe mocks base method.
func (m *MockHTTPServerInterface) ListenAndServe() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAndServe")
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenAndServe indicates an expected call of ListenAndServe.
func (mr *MockHTTPServerInterfaceMockRecorder) ListenAndServe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAndServe", reflect.TypeOf((*MockHTTPServerInterface)(nil).ListenAndServe))
}

// Shutdown mocks base method.
func (m *MockHTTPServerInterface) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockHTTPServerInterfaceMockRecorder) Shutdown(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockHTTPServerInterface)(nil).Shutdown), ctx)
}
